services:
  bot:
    depends_on:
      - grafana


  grafana:
    image: grafana/grafana-oss

    restart: unless-stopped

    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_AUTH_GOOGLE_CLIENT_SECRET: ${GF_AUTH_GOOGLE_CLIENT_SECRET}

    ports:
      - "3000:3000"

    volumes:
      - "grafana_volume:/var/lib/grafana"
      - "../configs/grafana:/etc/grafana"


volumes:
  grafana_volume:

