services:
  bot:
    depends_on:
      database:
        condition: service_healthy

    environment:
      DATA_SOURCE_HOST: database

  database:
    image: postgres

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

    environment:
      POSTGRES_USER: ${DATA_SOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATA_SOURCE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATA_SOURCE_NAME:-postgres}

    volumes:
      - "database_volume:/var/lib/postgresql/data"

volumes:
  database_volume:

